# Despotes build properties (fabric branch)
org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

mod_id=despotes
mod_name=Despotes
mod_version=v26.13-Alpha.1
mod_semver=26.13.0-Alpha.1
maven_group=dev.despotes
