org.gradle.jvmargs=-Xmx6G -XX:MaxMetaspaceSize=1G -XX:+UseParallelGC -Djava.net.preferIPv4Stack=true
org.gradle.java.installations.paths=C:/Program Files/Eclipse Adoptium/jdk-21.0.11.10-hotspot
mc_version=1.21.1
forge_version=52.1.16
mod_id=despotes
mod_name=Despotes
mod_version=v26.1-Alpha.3
mod_semver=26.1.0-Alpha.3
mod_group_id=dev.despotes
mod_license=Apache-2.0
