org.gradle.jvmargs=-Xmx1536m -XX:MaxMetaspaceSize=512m -XX:+UseParallelGC
mod_id=despotes
mod_name=Despotes
mod_version=v26.12-Alpha.2
mod_semver=26.12.0-Alpha.2
mod_group_id=dev.despotes
mod_license=Apache-2.0

org.gradle.java.installations.paths=C:/Users/Sails/Documents/Workspace/01-Active/Domain-Projects/Minecraft/Despotes/.tools/jdk-17.0.2
org.gradle.java.installations.auto-download=true
org.gradle.workers.max=2
